#!/bin/bash

read -p "Kasutaja: " user

read -sp "Parool: " password
echo
read -p "Grupp: " group

echo
sudo useradd -m $user
sudo groupadd -f $group
sudo sudo usermod -aG $group $user

echo "$user:$password" | sudo chpasswd
sudo mkdir /home/$user/kataloog
sudo touch /home/$user/kataloog/teretulemast_$user.txt
sudo chown $user:$group /home/$user/kataloog